spring:
   profiles:
      active: local

---      

spring:
   profiles: local
   kafka:
      consumer:
         bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
         key-deserializer: org.apache.kafka.common.deserialization.IntegerSerializer
         value-deserializer: org.apache.kafka.common.deserialization.StringSerializer
         group-id: consumer application group

